<?php namespace emeraldinspirations\library\ramDatabase;

use emeraldinspirations\library\unitTesting\systemCallInterception\SystemCallIntercetor;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-11-25 at 02:33:59.
 */
class exampleTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var example
     */
    protected $object;

    /**
     * @var SystemCallIntercept
     */
    protected $SystemCallIntercept = [];

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->setUp_SystemCallIntercept();
        $this->object = example::fromUnitTester(
            $this->SystemCallIntercept
        );
    }

    protected function setUp_SystemCallIntercept()
    {
        $this->SystemCallIntercept = (new SystemCallInterceptor())
            ->with__class_exists([
                'demo'=>TRUE
            ])
            ->with__class_loader([
                'demo'=>new class {
                    function run()
                    {
                        echo 'I Work!';
                    }
                }
            ]);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

}
